# Generated by Django 5.0 on 2023-12-16 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '7999999999'.", regex='^\\+?1?\\d{11,11}$')], verbose_name='Номер телефона')),
                ('mobile_operator_code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(blank=True, max_length=250, null=True, verbose_name='Метка')),
                ('time_zone', models.CharField(max_length=30, verbose_name='Временной пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(verbose_name='Время и дата начала рассылки')),
                ('end_date_time', models.DateTimeField(verbose_name='Время и дата окончания рассылки')),
                ('text', models.TextField(verbose_name='Текст рассылки')),
                ('client_mobile_operator_code', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Код мобильного оператора для фильтрации')),
                ('client_tag', models.CharField(blank=True, max_length=250, null=True, verbose_name='Метка клиентов для фильтрации')),
                ('client_time_zone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Временной пояс для фильтрации')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('status', models.CharField(default='NOT SEND', max_length=15, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.client', verbose_name='Получатель')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Посылка')),
            ],
        ),
    ]
