# Generated by Django 4.2.8 on 2023-12-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client_mobile_operator_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Код мобильного оператора для фильтрации'),
        ),
    ]
